name: rlfps_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - asn1crypto=0.24.0=py37_1003
  - blas=2.11=openblas
  - bzip2=1.0.8=h516909a_0
  - ca-certificates=2019.9.11=hecc5488_0
  - cairo=1.16.0=hfb77d84_1002
  - certifi=2019.9.11=py37_0
  - cffi=1.12.3=py37h8022711_0
  - chardet=3.0.4=py37_1003
  - cloudpickle=1.2.1=py_0
  - colorama=0.4.1=py_0
  - cryptography=2.7=py37h72c5cf5_0
  - cycler=0.10.0=py_1
  - dbus=1.13.6=he372182_0
  - decorator=4.4.0=py_0
  - docopt=0.6.2=py_1
  - expat=2.2.5=he1b5a44_1003
  - fastcache=1.1.0=py37h516909a_0
  - fire=0.1.3=py_1
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_0
  - fribidi=1.0.5=h516909a_1002
  - future=0.17.1=py37_1000
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.58.3=h6f030ca_1002
  - gmp=6.1.2=hf484d3e_1000
  - gmpy2=2.1.0b1=py37h04dde30_0
  - graphite2=1.3.13=hf484d3e_1000
  - graphviz=2.40.1=h5933667_1
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - harfbuzz=2.4.0=h9f30f68_2
  - icu=64.2=he1b5a44_0
  - idna=2.8=py37_1000
  - intel-openmp=2019.4=243
  - joblib=0.13.2=py_0
  - jpeg=9c=h14c3975_1001
  - jsonpickle=1.2=py_0
  - kiwisolver=1.1.0=py37hc9558a2_0
  - libblas=3.8.0=11_openblas
  - libcblas=3.8.0=11_openblas
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=11_openblas
  - liblapacke=3.8.0=11_openblas
  - libopenblas=0.3.6=h6e990d7_6
  - libpng=1.6.37=hed695b0_0
  - libprotobuf=3.9.0=h8b12597_0
  - libsodium=1.0.17=h516909a_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h57b8799_1003
  - libtool=2.4.6=h14c3975_1002
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=hee79883_2
  - lz4-c=1.8.3=he1b5a44_1001
  - matplotlib=3.1.1=py37_1
  - matplotlib-base=3.1.1=py37he7580a8_1
  - mkl=2019.4=243
  - mpc=1.1.0=hb20f59a_1006
  - mpfr=4.0.2=ha14ba45_0
  - mpmath=1.1.0=py_0
  - munch=2.3.2=py_0
  - ncurses=6.1=hf484d3e_1002
  - networkx=1.11=py37_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.16.4=py37h95a1406_0
  - olefile=0.46=py_0
  - openssl=1.1.1c=h516909a_0
  - packaging=19.2=py_0
  - pandas=0.24.2=py37hb3f55d8_0
  - pango=1.42.4=he7ab937_0
  - pcre=8.41=hf484d3e_1003
  - pillow=6.1.0=py37he7afcd5_0
  - pip=19.2.1=py37_0
  - pixman=0.38.0=h516909a_1003
  - protobuf=3.9.0=py37he1b5a44_0
  - pthread-stubs=0.4=h14c3975_1001
  - py-cpuinfo=5.0.0=py_0
  - pycparser=2.19=py37_1
  - pydot=1.4.1=py37_1001
  - pydotplus=2.0.2=pyhd1c1de3_3
  - pymongo=3.8.0=py37he1b5a44_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py37hcca6a23_0
  - pysocks=1.7.0=py37_0
  - python=3.7.3=h33d41f4_1
  - python-dateutil=2.8.0=py_0
  - pytorch-cpu=1.1.0=py3.7_cpu_0
  - pytz=2019.2=py_0
  - pyzmq=18.0.2=py37h1768529_2
  - qt=5.9.7=h0c104cb_3
  - readline=8.0=hf8c457e_0
  - requests=2.22.0=py37_1
  - scikit-learn=0.21.2=py37h22eb022_0
  - scikit-optimize=0.5.2=py_0
  - scipy=1.2.1=py37h09a28d5_1
  - setuptools=41.0.1=py37_0
  - sip=4.19.8=py37hf484d3e_1000
  - six=1.12.0=py37_1000
  - sqlite=3.29.0=hcee41ef_0
  - sympy=1.4=py37_0
  - tensorboardx=1.8=py_0
  - tk=8.6.9=hed695b0_1002
  - torchfile=0.1.0=py_0
  - torchvision-cpu=0.3.0=py37_cuNone_1
  - tornado=6.0.3=py37h516909a_0
  - tqdm=4.32.2=py_0
  - urllib3=1.25.3=py37_0
  - visdom=0.1.8.8=0
  - websocket-client=0.56.0=py37_0
  - wheel=0.33.4=py37_0
  - wrapt=1.11.2=py37h516909a_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.8=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxpm=3.5.12=h14c3975_1002
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - zeromq=4.3.2=he1b5a44_2
  - zlib=1.2.11=h516909a_1005
  - zstd=1.4.0=h3b9ef0a_0
prefix: /home/xli4217/miniconda3/envs/rlfps_env

